name: Deploy Azure Functions

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Azure CLI
      uses: azure/setup-azure-cli@v1

    - name: Login to Azure
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        az login --service-principal -u ${{ secrets.AZCRED.clientId }} -p ${{ secrets.AZCRED.clientSecret }} --tenant ${{ secrets.AZCRED.tenantId }}

    - name: Deploy to Azure Functions
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        az functionapp deployment source config-zip -g powerAuto -n myApp --src deployment/func
